services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/home/agentuser
    command: tail -f /dev/null
    network_mode: host

  # Vector Database
  # chroma:
  #   image: chromadb/chroma:latest
  #   container_name: chroma
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./chroma_data:/data
